# first step, build react
FROM node:alpine as react-build
WORKDIR /app
ADD package*.json .
RUN npm install
ADD . .
ARG NODE_ENV 
ENV NODE_ENV = $NODE_ENV
RUN npm run build

# secondly, build nginx and move react build to nginx server folder
FROM nginx:alpine
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/build /usr/share/nginx/html
