version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src:ro
    env_file:
      - ./.env
    container_name: frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    
    